// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

export const MONACO_EDITOR_THEME = {
    base: 'vs',
    inherit: true,
    rules: [],
    colors: {
        'editor.background': '#F9FBFC',
    },
};

export const RESIZEABLE_ENABLE = {
    top: false,
    right: false,
    bottom: true,
    left: false,
    topRight: false,
    bottomRight: false,
    bottomLeft: false,
    topLeft: false,
};

export const THEME_NAME = 'theme-name';

export const DEFAULT_SUGGESTIONS = [
    { label: 'add', insertText: 'add', detail: '提示' },
    { label: 'after', insertText: 'after', detail: '提示' },
    { label: 'all', insertText: 'all', detail: '提示' },
    { label: 'alter', insertText: 'alter', detail: '提示' },
    { label: 'and', insertText: 'and', detail: '提示' },
    { label: 'append', insertText: 'append', detail: '提示' },
    { label: 'as', insertText: 'as', detail: '提示' },
    { label: 'authors', insertText: 'authors', detail: '提示' },
    { label: 'begin', insertText: 'begin', detail: '提示' },
    { label: 'between', insertText: 'between', detail: '提示' },
    { label: 'bigint', insertText: 'bigint', detail: '提示' },
    { label: 'boolean', insertText: 'boolean', detail: '提示' },
    { label: 'hdfs', insertText: 'hdfs', detail: '提示' },
    { label: 'by', insertText: 'by', detail: '提示' },
    { label: 'char', insertText: 'char', detail: '提示' },
    { label: 'character', insertText: 'character', detail: '提示' },
    { label: 'column', insertText: 'column', detail: '提示' },
    { label: 'columns', insertText: 'columns', detail: '提示' },
    { label: 'comment', insertText: 'comment', detail: '提示' },
    { label: 'commit', insertText: 'commit', detail: '提示' },
    { label: 'committed', insertText: 'committed', detail: '提示' },
    { label: 'config', insertText: 'config', detail: '提示' },
    { label: 'count', insertText: 'count', detail: '提示' },
    { label: 'create', insertText: 'create', detail: '提示' },
    { label: 'cross', insertText: 'cross', detail: '提示' },
    { label: 'database', insertText: 'database', detail: '提示' },
    { label: 'databases', insertText: 'databases', detail: '提示' },
    { label: 'date', insertText: 'date', detail: '提示' },
    { label: 'datetime', insertText: 'datetime', detail: '提示' },
    { label: 'decimal', insertText: 'decimal', detail: '提示' },
    { label: 'delete', insertText: 'delete', detail: '提示' },
    { label: 'desc', insertText: 'desc', detail: '提示' },
    { label: 'double', insertText: 'double', detail: '提示' },
    { label: 'drop', insertText: 'drop', detail: '提示' },
    { label: 'else', insertText: 'else', detail: '提示' },
    { label: 'enable', insertText: 'enable', detail: '提示' },
    { label: 'end', insertText: 'end', detail: '提示' },
    { label: 'engine', insertText: 'engine', detail: '提示' },
    { label: 'engines', insertText: 'engines', detail: '提示' },
    { label: 'except', insertText: 'except', detail: '提示' },
    { label: 'exclude', insertText: 'exclude', detail: '提示' },
    { label: 'exists', insertText: 'exists', detail: '提示' },
    { label: 'explain', insertText: 'explain', detail: '提示' },
    { label: 'external', insertText: 'external', detail: '提示' },
    { label: 'float', insertText: 'float', detail: '提示' },
    { label: 'format', insertText: 'format', detail: '提示' },
    { label: 'from', insertText: 'from', detail: '提示' },
    { label: 'grant', insertText: 'grant', detail: '提示' },
    { label: 'grants', insertText: 'grants', detail: '提示' },
    { label: 'group', insertText: 'group', detail: '提示' },
    { label: 'hash', insertText: 'hash', detail: '提示' },
    { label: 'having', insertText: 'having', detail: '提示' },
    { label: 'inner', insertText: 'inner', detail: '提示' },
    { label: 'insert', insertText: 'insert', detail: '提示' },
    { label: 'int', insertText: 'int', detail: '提示' },
    { label: 'integer', insertText: 'integer', detail: '提示' },
    { label: 'into', insertText: 'into', detail: '提示' },
    { label: 'is', insertText: 'is', detail: '提示' },
    { label: 'isnull', insertText: 'isnull', detail: '提示' },
    { label: 'join', insertText: 'join', detail: '提示' },
    { label: 'key', insertText: 'key', detail: '提示' },
    { label: 'keys', insertText: 'keys', detail: '提示' },
    { label: 'last', insertText: 'last', detail: '提示' },
    { label: 'left', insertText: 'left', detail: '提示' },
    { label: 'less', insertText: 'less', detail: '提示' },
    { label: 'like', insertText: 'like', detail: '提示' },
    { label: 'limit', insertText: 'limit', detail: '提示' },
    { label: 'list', insertText: 'list', detail: '提示' },
    { label: 'load', insertText: 'load', detail: '提示' },
    { label: 'max', insertText: 'max', detail: '提示' },
    { label: 'merge', insertText: 'merge', detail: '提示' },
    { label: 'min', insertText: 'min', detail: '提示' },
    { label: 'modify', insertText: 'modify', detail: '提示' },
    { label: 'month', insertText: 'month', detail: '提示' },
    { label: 'no', insertText: 'no', detail: '提示' },
    { label: 'not', insertText: 'not', detail: '提示' },
    { label: 'null', insertText: 'null', detail: '提示' },
    { label: 'nulls', insertText: 'nulls', detail: '提示' },
    { label: 'offset', insertText: 'offset', detail: '提示' },
    { label: 'on', insertText: 'on', detail: '提示' },
    { label: 'only', insertText: 'only', detail: '提示' },
    { label: 'open', insertText: 'open', detail: '提示' },
    { label: 'or', insertText: 'or', detail: '提示' },
    { label: 'order', insertText: 'order', detail: '提示' },
    { label: 'partition', insertText: 'partition', detail: '提示' },
    { label: 'partitions', insertText: 'partitions', detail: '提示' },
    { label: 'properties', insertText: 'properties', detail: '提示' },
    { label: 'property', insertText: 'property', detail: '提示' },
    { label: 'range', insertText: 'range', detail: '提示' },
    { label: 'range', insertText: 'range', detail: '提示' },
    { label: 'revoke', insertText: 'revoke', detail: '提示' },
    { label: 'right', insertText: 'right', detail: '提示' },
    { label: 'role', insertText: 'role', detail: '提示' },
    { label: 'roles', insertText: 'roles', detail: '提示' },
    { label: 'row', insertText: 'row', detail: '提示' },
    { label: 'rows', insertText: 'rows', detail: '提示' },
    { label: 'schema', insertText: 'schema', detail: '提示' },
    { label: 'schemas', insertText: 'schemas', detail: '提示' },
    { label: 'second', insertText: 'second', detail: '提示' },
    { label: 'select', insertText: 'select', detail: '提示' },
    { label: 'set', insertText: 'set', detail: '提示' },
    { label: 'sets', insertText: 'sets', detail: '提示' },
    { label: 'show', insertText: 'show', detail: '提示' },
    { label: 'stream', insertText: 'stream', detail: '提示' },
    { label: 'string', insertText: 'string', detail: '提示' },
    { label: 'sum', insertText: 'sum', detail: '提示' },
    { label: 'table', insertText: 'table', detail: '提示' },
    { label: 'tables', insertText: 'tables', detail: '提示' },
    { label: 'than', insertText: 'than', detail: '提示' },
    { label: 'then', insertText: 'then', detail: '提示' },
    { label: 'timestamp', insertText: 'timestamp', detail: '提示' },
    { label: 'true', insertText: 'true', detail: '提示' },
    { label: 'truncate', insertText: 'truncate', detail: '提示' },
    { label: 'type', insertText: 'type', detail: '提示' },
    { label: 'types', insertText: 'types', detail: '提示' },
    { label: 'union', insertText: 'union', detail: '提示' },
    { label: 'unique', insertText: 'unique', detail: '提示' },
    { label: 'unsigned', insertText: 'unsigned', detail: '提示' },
    { label: 'use', insertText: 'use', detail: '提示' },
    { label: 'user', insertText: 'user', detail: '提示' },
    { label: 'using', insertText: 'using', detail: '提示' },
    { label: 'update', insertText: 'update', detail: '提示' },
    { label: 'value', insertText: 'value', detail: '提示' },
    { label: 'values', insertText: 'values', detail: '提示' },
    { label: 'varchar', insertText: 'varchar', detail: '提示' },
    { label: 'variables', insertText: 'variables', detail: '提示' },
    { label: 'view', insertText: 'view', detail: '提示' },
    { label: 'when', insertText: 'when', detail: '提示' },
    { label: 'where', insertText: 'where', detail: '提示' },
    { label: 'with', insertText: 'with', detail: '提示' },
    { label: 'write', insertText: 'write', detail: '提示' },
    { label: 'year', insertText: 'year', detail: '提示' },
    { label: 'matched', insertText: 'matched', detail: '提示' },
    { label: 'run', insertText: 'run', detail: '提示' },
    { label: 'tasks', insertText: 'tasks', detail: '提示' },
    { label: 'update', insertText: 'update', detail: '提示' },
    { label: 'stage', insertText: 'stage', detail: '提示' },
    { label: 'stages', insertText: 'stages', detail: '提示' },
    { label: 'url', insertText: 'url', detail: '提示' },
    { label: 'storage_options', insertText: 'storage_options', detail: '提示' },
    { label: 'file_format', insertText: 'file_format', detail: '提示' },
    { label: 'copy_options', insertText: 'copy_options', detail: '提示' },
    { label: 'jobflow', insertText: 'jobflow', detail: '提示' },
    { label: 'schedule', insertText: 'schedule', detail: '提示' },
    { label: 'copy', insertText: 'copy', detail: '提示' },
    { label: 'grants', insertText: 'grants', detail: '提示' },
    { label: 'cron', insertText: 'cron', detail: '提示' },
    { label: 'options', insertText: 'options', detail: '提示' },
    { label: 'job', insertText: 'job', detail: '提示' },
    { label: 'unset', insertText: 'unset', detail: '提示' },
    { label: 'remove', insertText: 'remove', detail: '提示' },
    { label: 'terse', insertText: 'terse', detail: '提示' },
    { label: 'jobs', insertText: 'jobs', detail: '提示' },
    { label: 'starts', insertText: 'starts', detail: '提示' },
    { label: 'account', insertText: 'account', detail: '提示' },
    { label: 'jobflows', insertText: 'jobflows', detail: '提示' },
    { label: 'call', insertText: 'call', detail: '提示' },
    { label: 'at', insertText: 'at', detail: '提示' },
    { label: 'history', insertText: 'history', detail: '提示' },
    { label: 'snapshots', insertText: 'snapshots', detail: '提示' },
    { label: 'clone', insertText: 'clone', detail: '提示' },
    { label: 'stream', insertText: 'stream', detail: '提示' },
    { label: 'before', insertText: 'before', detail: '提示' },
    { label: 'append_only', insertText: 'append_only', detail: '提示' },
    { label: 'streams', insertText: 'streams', detail: '提示' },
    { label: 'dropped', insertText: 'dropped', detail: '提示' },
    { label: 'array', insertText: 'array', detail: '提示' },
    { label: 'map', insertText: 'map', detail: '提示' },
    { label: 'struct', insertText: 'struct', detail: '提示' },
    { label: 'field', insertText: 'field', detail: '提示' },
    { label: 'refresh', insertText: 'refresh', detail: '提示' },
    { label: 'mount', insertText: 'mount', detail: '提示' },
    { label: 'files', insertText: 'files', detail: '提示' },
    { label: 'cache', insertText: 'cache', detail: '提示' },
    { label: 'granted', insertText: 'granted', detail: '提示' },
    { label: 'cached', insertText: 'cached', detail: '提示' },
    { label: 'queue', insertText: 'queue', detail: '提示' },
    { label: 'queues', insertText: 'queues', detail: '提示' },
    { label: 'sessionlabel', insertText: 'sessionlabel', detail: '提示' },
    { label: 'extended', insertText: 'extended', detail: '提示' },
];
